export const months = [
  "Januar", "Februar", "März", "April", "Mai", "Juni",
  "Juli", "August", "September", "Oktober", "November", "Dezember"
];

export const calendar = [
  {
    month: "Januar",
    icon: "❄️",
    vorziehen: [
      { name: "Paprika", wo: "drinnen", tipp: "Braucht Wärme (20–25°C) zum Keimen, lange Anzuchtzeit!" },
      { name: "Kohlrabi (1. Satz)", wo: "drinnen", tipp: "Frühe Sorte, z.B. 'Azur Star'" },
    ],
    pflanzen: [],
    ernten: [
      { name: "Feldsalat", tipp: "Falls im Herbst gesät" },
    ],
    tipp: "Saatgut bestellen & Anzuchterde besorgen! Paprika und Kohlrabi brauchen einen frühen Start.",
    beet: null,
  },
  {
    month: "Februar",
    icon: "🌱",
    vorziehen: [
      { name: "Paprika (nachholen)", wo: "drinnen", tipp: "Spätestens jetzt ansetzen" },
      { name: "Kohlrabi (2. Satz)", wo: "drinnen", tipp: "Für gestaffelte Ernte" },
      { name: "Salat (früh)", wo: "drinnen", tipp: "Kopfsalat oder Schnittsalat" },
    ],
    pflanzen: [],
    ernten: [
      { name: "Feldsalat", tipp: "Letzter Ernteansatz vom Herbst" },
    ],
    tipp: "Anzuchtstation einrichten: Zimmergewächshaus + Wärmeunterlage empfehlenswert.",
    beet: null,
  },
  {
    month: "März",
    icon: "🌿",
    vorziehen: [
      { name: "Tomaten", wo: "drinnen", tipp: "Ab Mitte März; mind. 8 Wochen vor Auspflanzen" },
      { name: "Gurken", wo: "drinnen", tipp: "Erst Ende März, wachsen schnell!" },
      { name: "Zucchini", wo: "drinnen", tipp: "Ende März, wächst rasant" },
      { name: "Kürbis", wo: "drinnen", tipp: "Ende März; für Freiland" },
      { name: "Salat", wo: "drinnen", tipp: "2. Satz für Hochbeet" },
      { name: "Kohlrabi (3. Satz)", wo: "drinnen", tipp: "Für späte Ernte" },
    ],
    pflanzen: [
      { name: "Radieschen", wo: "überdachtes Hochbeet", tipp: "Direktsaat möglich, mag Kühle" },
      { name: "Salat (Jungpflanzen)", wo: "überdachtes Hochbeet", tipp: "Vorgezogene Pflanzen aus Februar" },
    ],
    ernten: [],
    tipp: "Hochbeet im überdachten Bereich kann schon bepflanzt werden – geschützt vor Frost.",
    beet: "überdacht: Radieschen + Salat",
  },
  {
    month: "April",
    icon: "🌸",
    vorziehen: [
      { name: "Kürbis (nochmals)", wo: "drinnen", tipp: "Falls März-Satz nicht geklappt hat" },
    ],
    pflanzen: [
      { name: "Kohlrabi Jungpflanzen", wo: "überdachtes Hochbeet", tipp: "Aus Jan/Feb-Anzucht" },
      { name: "Salat (Folgesatz)", wo: "nicht überdacht", tipp: "Ab Mitte April, wenn kein Frost mehr erwartet" },
      { name: "Radieschen", wo: "nicht überdacht", tipp: "Direktsaat ab Mitte April" },
      { name: "Erbsen", wo: "nicht überdacht", tipp: "Direktsaat – gut für Anfänger!" },
      { name: "Möhren", wo: "nicht überdacht", tipp: "Direktsaat, mag lockere Erde" },
    ],
    ernten: [
      { name: "Radieschen (März-Satz)", tipp: "Ca. 3–4 Wochen nach Aussaat" },
      { name: "Salat (erste Blätter)", tipp: "Schnittsalat nach Bedarf ernten" },
    ],
    tipp: "Tomaten, Paprika, Gurken stehen drinnen und wachsen heran – regelmäßig pikieren!",
    beet: "überdacht: Kohlrabi | offen: Salat, Radieschen, Erbsen, Möhren",
  },
  {
    month: "Mai",
    icon: "☀️",
    vorziehen: [],
    pflanzen: [
      { name: "Tomaten", wo: "überdachtes Hochbeet", tipp: "Ab Mitte Mai nach den Eisheiligen (11.–15. Mai)!" },
      { name: "Paprika", wo: "überdachtes Hochbeet", tipp: "Wärmeliebend – nach Eisheiligen" },
      { name: "Gurken", wo: "überdachtes Hochbeet", tipp: "Ideal unter dem Dach" },
      { name: "Zucchini", wo: "Freiland/Garten", tipp: "Braucht viel Platz!" },
      { name: "Kürbis", wo: "Freiland/Garten", tipp: "Sehr platzintensiv, ab Mitte Mai" },
      { name: "Salat (3. Satz)", wo: "nicht überdacht", tipp: "Gestaffelt alle 3 Wochen säen" },
    ],
    ernten: [
      { name: "Radieschen", tipp: "Laufende Ernte" },
      { name: "Salat", tipp: "Schnittsalat oder Köpfe" },
      { name: "Erbsen (Zuckerschoten)", tipp: "Falls früh gepflanzt" },
      { name: "Kohlrabi (früh)", tipp: "Aus März-Anzucht, wenn Knollen faustgroß" },
    ],
    tipp: "🌡️ ACHTUNG EISHEILIGE (11.–15. Mai): Erst danach empfindliche Pflanzen raus! Tomaten unter Dach früher.",
    beet: "überdacht: Tomaten, Paprika, Gurken | offen: Salat, Möhren",
  },
  {
    month: "Juni",
    icon: "🌞",
    vorziehen: [
      { name: "Salat (Herbstsatz)", wo: "drinnen/halbschatten", tipp: "Hitzeresistente Sorte wählen" },
      { name: "Kohlrabi (Herbstsatz)", wo: "drinnen", tipp: "Für Herbsternte" },
    ],
    pflanzen: [
      { name: "Salat (Folge)", wo: "nicht überdacht", tipp: "Immer staffeln!" },
      { name: "Radieschen (Folge)", wo: "nicht überdacht", tipp: "Bis Ende Juni noch möglich" },
      { name: "Buschbohnen", wo: "nicht überdacht", tipp: "Direktsaat, einfach & ertragreich" },
      { name: "Rote Bete", wo: "nicht überdacht", tipp: "Direktsaat bis Ende Juni" },
    ],
    ernten: [
      { name: "Radieschen", tipp: "Laufend" },
      { name: "Salat", tipp: "Laufend" },
      { name: "Kohlrabi", tipp: "Aus Frühjahrsanzucht" },
      { name: "Erbsen", tipp: "Haupternte" },
      { name: "Möhren (Frühsorten)", tipp: "Wenn fingerdick" },
    ],
    tipp: "Tomaten, Paprika und Gurken regelmäßig gießen und Tomaten ausgeizen!",
    beet: "überdacht: Tomaten/Paprika/Gurken wachsen | offen: Bohnen, Bete",
  },
  {
    month: "Juli",
    icon: "🍅",
    vorziehen: [
      { name: "Salat (Herbst)", wo: "drinnen/kühl", tipp: "Für September-Pflanzung" },
      { name: "Pak Choi / Asiasalat", wo: "direkt", tipp: "Tolles Anfänger-Gemüse für Herbst" },
    ],
    pflanzen: [
      { name: "Kohlrabi (Herbst)", wo: "freie Stellen", tipp: "Nach Frühernte-Lücken nachpflanzen" },
      { name: "Spinat", wo: "nicht überdacht", tipp: "Direktsaat für Herbst" },
      { name: "Feldsalat", wo: "nicht überdacht", tipp: "Ab Ende Juli für Winterernte" },
    ],
    ernten: [
      { name: "🍅 Erste Tomaten!", tipp: "Cherry-Tomaten zuerst reif" },
      { name: "Gurken", tipp: "Regelmäßig ernten, sonst werden sie bitter" },
      { name: "Zucchini", tipp: "Klein ernten (20 cm) = zarter Geschmack" },
      { name: "Kohlrabi", tipp: "Haupternte" },
      { name: "Salat", tipp: "Laufend" },
      { name: "Buschbohnen", tipp: "Haupternte" },
      { name: "Möhren", tipp: "Wenn dick genug" },
    ],
    tipp: "Hochsaison! Zucchini täglich kontrollieren – wächst sehr schnell!",
    beet: "Alle Beete in voller Produktion",
  },
  {
    month: "August",
    icon: "🥒",
    vorziehen: [],
    pflanzen: [
      { name: "Salat (Herbst)", wo: "nicht überdacht", tipp: "Letzte Chance für Herbsternte" },
      { name: "Feldsalat", wo: "nicht überdacht", tipp: "Direktsaat für Winter" },
      { name: "Spinat", wo: "nicht überdacht", tipp: "Herbst-/Winterernte" },
      { name: "Radieschen (Herbst)", wo: "nicht überdacht", tipp: "Noch eine schnelle Runde!" },
    ],
    ernten: [
      { name: "Tomaten", tipp: "Haupternte – Überschuss einkochen!" },
      { name: "Paprika", tipp: "Grün oder reif roten ernten" },
      { name: "Gurken", tipp: "Täglich kontrollieren" },
      { name: "Zucchini", tipp: "Laufend" },
      { name: "Kürbis", tipp: "Noch nicht – Stiel muss verkorkt sein" },
      { name: "Rote Bete", tipp: "Ab ca. Faustgröße" },
      { name: "Möhren", tipp: "Laufend" },
      { name: "Buschbohnen", tipp: "2. Ernte" },
    ],
    tipp: "Nach Ernte freiwerdende Flächen sofort mit Feldsalat oder Spinat nachsäen!",
    beet: "überdacht: Tomaten/Paprika Hochsaison | offen: Nachsaat für Herbst",
  },
  {
    month: "September",
    icon: "🍂",
    vorziehen: [],
    pflanzen: [
      { name: "Feldsalat (letzte Chance)", wo: "nicht überdacht", tipp: "Bis Mitte September noch säen" },
      { name: "Winterportulak", wo: "überdachtes Hochbeet", tipp: "Tolles kältehartes Wintergemüse" },
      { name: "Asiasalate", wo: "überdachtes Hochbeet", tipp: "Mizuna, Pak Choi – sehr einfach!" },
    ],
    ernten: [
      { name: "Tomaten", tipp: "Letzte Ernte, grüne Tomaten für Chutney" },
      { name: "Paprika", tipp: "Alles vor dem ersten Frost ernten" },
      { name: "Kürbis 🎃", tipp: "Wenn Stiel verkorkt und Schale hart – jetzt ernten!" },
      { name: "Zucchini (letzter)", tipp: "Vor Frost ernten" },
      { name: "Möhren", tipp: "Komplett ernten oder im Beet lagern" },
      { name: "Rote Bete", tipp: "Vor starkem Frost ernten" },
      { name: "Salat", tipp: "Laufend" },
      { name: "Kohlrabi (Herbst)", tipp: "Ab jetzt" },
    ],
    tipp: "Kürbisse nach Ernte trocken und kühl lagern – halten Monate! Tomaten-Pflanzen nach Saison kompostieren.",
    beet: "Räumung + Nachsaat Wintergemüse",
  },
  {
    month: "Oktober",
    icon: "🎃",
    vorziehen: [],
    pflanzen: [
      { name: "Knoblauch", wo: "Hochbeet (beide)", tipp: "Jetzt stecken für nächstes Jahr!" },
      { name: "Zwiebeln (Steckzwiebeln)", wo: "nicht überdacht", tipp: "Herbststeckung für Frühjahrsernte" },
    ],
    ernten: [
      { name: "Feldsalat", tipp: "Erste Blätter" },
      { name: "Asiasalate", tipp: "Im überdachten Beet laufend" },
      { name: "Kohlrabi (Herbst)", tipp: "Letzte Ernte vor Frost" },
      { name: "Spinat", tipp: "Vor Frost ernten oder mulchen" },
      { name: "Winterportulak", tipp: "Kälteverträglich, kann bleiben" },
    ],
    tipp: "Beete abräumen, kompostieren und mit Mulch oder Winterbegrünung abdecken.",
    beet: "Abrüsten + Knoblauch stecken",
  },
  {
    month: "November",
    icon: "🌧️",
    vorziehen: [],
    pflanzen: [],
    ernten: [
      { name: "Feldsalat", tipp: "Verträgt leichten Frost" },
      { name: "Winterportulak", tipp: "Im überdachten Beet ernten" },
      { name: "Asiasalate", tipp: "Im überdachten Beet – bis Frost" },
    ],
    tipp: "Ruhephase. Saatgut-Kataloge studieren & Beetplanung für nächstes Jahr beginnen. Rhabarber-Wurzeln jetzt pflanzen!",
    beet: "Überdachtes Beet: Wintergemüse",
  },
  {
    month: "Dezember",
    icon: "🎄",
    vorziehen: [],
    pflanzen: [],
    ernten: [
      { name: "Feldsalat", tipp: "Wenn kein extremer Frost" },
      { name: "Winterportulak", tipp: "Im überdachten Beet" },
    ],
    tipp: "Gartenplanung für 2027! Saatgut bestellen, Beetplan zeichnen, Fruchtfolge planen.",
    beet: "Ruhe – aber Feldsalat & Portulak ernten",
  },
];

export const tagColors = {
  drinnen: "bg-amber-100 text-amber-800 border border-amber-300",
  "überdachtes Hochbeet": "bg-sky-100 text-sky-800 border border-sky-300",
  "nicht überdacht": "bg-green-100 text-green-700 border border-green-300",
  "Freiland/Garten": "bg-lime-100 text-lime-700 border border-lime-300",
  "freie Stellen": "bg-teal-100 text-teal-700 border border-teal-300",
  "Hochbeet (beide)": "bg-purple-100 text-purple-700 border border-purple-300",
  "direkt": "bg-green-100 text-green-700 border border-green-300",
  "drinnen/halbschatten": "bg-amber-100 text-amber-800 border border-amber-300",
  "drinnen/kühl": "bg-amber-100 text-amber-800 border border-amber-300",
};
